#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$OMG" ]]; then
    OMG=$(dappCreate tss-deploy OMG "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "OMG=$OMG"
    export OMG
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/tss/deploy-ilk" "OMG" "${1:-"A"}" "GemJoin2"
