#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$ETH" ]]; then
    ETH=$(dappCreate tss-deploy WETH9_)
    log "ETH=$ETH"
    export ETH
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/tss/deploy-ilk" "ETH" "${1:-"A"}" "GemJoin"
