#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

{ test -z "$1" || test -z "$3"; } && exit 1

tok=$1
if [[ -n "$2" ]]; then
    ilk="${1}-${2}"
    ilkVar="${1}_${2}"
else
    ilk="${1}"
    ilkVar="${1}"
fi
ilkJoin=$3 # adapter contract name
decimals=$4

# Deploy ETH ilk (adapter, spotter, flip and init variables)
test -z "$MCT_DEPLOY" && exit 1

MCT_VAT=$(seth call "$MCT_DEPLOY" "vat()(address)")
if [[ "$decimals" != "" ]]; then
    contract=$(dappCreate dss-deploy "$ilkJoin" "$MCT_VAT" "$(seth --to-bytes32 "$(seth --from-ascii "$ilk")")" "$(eval echo "\$${tok}")" "$decimals")
else
    contract=$(dappCreate dss-deploy "$ilkJoin" "$MCT_VAT" "$(seth --to-bytes32 "$(seth --from-ascii "$ilk")")" "$(eval echo "\$${tok}")")
fi
eval export "\MCT_JOIN_${ilkVar}=${contract}"
log "MCT_JOIN_${ilkVar}=$(eval "echo ${contract}")"

sethSend "$MCT_DEPLOY" "deployCollateral(bytes32,address,address)" "$(seth --to-bytes32 "$(seth --from-ascii "$ilk")")" "$(eval echo "\$MCT_JOIN_${ilkVar}")" "$(eval echo "\$PIP_${tok}")"
while IFS=$'\n' read -r line; do data+=("$line"); done < <(seth call "$MCT_DEPLOY" "ilks(bytes32)(address,address)" "$(seth --to-bytes32 "$(seth --from-ascii "$ilk")")")
eval export "\MCT_FLIP_${ilkVar}=${data[0]}"

cat > "$OUT_DIR/load-ilk-addr-temp" << EOF
#!/bin/bash
export PIP_${tok}=$(eval echo "\$PIP_${tok}")
export ${tok}=$(eval echo "\$${tok}")
export MCT_JOIN_${ilkVar}=$(eval echo "\$MCT_JOIN_${ilkVar}")
export MCT_FLIP_${ilkVar}=$(eval echo "\$MCT_FLIP_${ilkVar}")
EOF
