#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$ZRX" ]]; then
    ZRX=$(dappCreate tss-deploy ZRX "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "ZRX=$ZRX"
    export ZRX
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/tss/deploy-ilk" "ZRX" "${1:-"A"}" "GemJoin"
